apiVersion: v1
kind: Service
metadata:
  name: doomsday-frontend
  namespace: default
  labels:
    app: doomsday-frontend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: doomsday-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: doomsday-frontend-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: doomsday-frontend
        version: v1
    spec:
      containers:
      - image: nrjpoddar/doomsday-frontend
        imagePullPolicy: Always
        name: doomsday-frontend
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tcp-dumps
          name: dump-dir
      volumes:
      - name: dump-dir
        hostPath:
          path: /doomsday/frontend
---
apiVersion: v1
kind: Service
metadata:
  name: doomsday-clock
  namespace: default
  labels:
    app: doomsday-clock
spec:
  ports:
  - name: http-clock
    port: 8080
    targetPort: 8080
  selector:
    app: doomsday-clock
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: doomsday-clock-v1
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: doomsday-clock
        version: v1
    spec:
      containers:
      - image: nrjpoddar/doomsday-clock
        imagePullPolicy: Always
        name: doomsday-clock
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tcp-dumps
          name: dump-dir
      volumes:
      - name: dump-dir
        hostPath:
          path: /doomsday/clock
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: doomsday-clock-v2
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: doomsday-clock
        version: v2
    spec:
      containers:
      - image: nrjpoddar/doomsday-clock
        imagePullPolicy: Always
        name: doomsday-clock
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tcp-dumps
          name: dump-dir
        args:
        - "Five Minutes"
      volumes:
      - name: dump-dir
        hostPath:
          path: /doomsday/clock
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: doomsday-gateway
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /doomsday
        backend:
          serviceName: doomsday-frontend
          servicePort: 8080
---
