apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: doomsday-frontend-default
spec:
  destination:
    service: doomsday-frontend.default.svc.cluster.local
  precedence: 1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: doomsday-clock-default
spec:
  destination:
    service: doomsday-clock.default.svc.cluster.local
  precedence: 1
  route:
  - labels:
      version: v1
---
